// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDhDvLBBQY4pkc94EXe5cQp_3gY7Dz6wM',
    appId: '1:111825259893:web:c41cae36fe71dcdeb2173c',
    messagingSenderId: '111825259893',
    projectId: 'smart-attendance-c8ff0',
    authDomain: 'smart-attendance-c8ff0.firebaseapp.com',
    storageBucket: 'smart-attendance-c8ff0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2rGja4xI27g3a8vMrwFo6BglizfzW2Dg',
    appId: '1:111825259893:android:20c6c16cadb4e7f2b2173c',
    messagingSenderId: '111825259893',
    projectId: 'smart-attendance-c8ff0',
    storageBucket: 'smart-attendance-c8ff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhlV7iGLfiRGDiLfOJ4N8hX_yPYgr_wvU',
    appId: '1:111825259893:ios:f5cd202e38b78f78b2173c',
    messagingSenderId: '111825259893',
    projectId: 'smart-attendance-c8ff0',
    storageBucket: 'smart-attendance-c8ff0.appspot.com',
    iosClientId: '111825259893-p3q4i8vtqpcgdga8ducditj0j9hbaoas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhlV7iGLfiRGDiLfOJ4N8hX_yPYgr_wvU',
    appId: '1:111825259893:ios:f5cd202e38b78f78b2173c',
    messagingSenderId: '111825259893',
    projectId: 'smart-attendance-c8ff0',
    storageBucket: 'smart-attendance-c8ff0.appspot.com',
    iosClientId: '111825259893-p3q4i8vtqpcgdga8ducditj0j9hbaoas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
